#!/bin/sh

output=$1
name=$(basename "$0")

show_usage() {
  echo "usage: $name file"
}

show_version() {
  echo "$name version 1.0.0"
}

xcrecord() {
  xcrun_destination=$(mktemp)
  xcrun simctl io booted recordVideo "$xcrun_destination"

  palette=$(mktemp "$TMPDIR$(uuidgen).png")
  paletteops="stats_mode=diff"
  filters=fps=10,scale=-1:480:flags=lanczos
  ffmpeg_destination="$(mktemp "$TMPDIR""$(uuidgen)".gif)"

  ffmpeg -loglevel quiet \
    -i "$xcrun_destination" \
    -vf "$filters,palettegen=$paletteops" \
    -y "$palette"
  ffmpeg -loglevel quiet \
    -i "$xcrun_destination" \
    -i "$palette" \
    -filter_complex "$filters [x]; [x][1:v] paletteuse" \
    -y "$ffmpeg_destination"

  gifsicle --optimize=3 --output "$output" "$ffmpeg_destination"

  rm -r "$xcrun_destination" "$palette"
}

case $1 in
  -v|--version|version)
    show_version
    exit
    ;;
  ?*)
    xcrecord
    ;;
  *)
    show_usage
    exit 1
    ;;
esac
